apis/urls.py
# apis/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import PokemonViewSet, TypeViewSet, UserViewSet, ActiveUser

router = DefaultRouter()
router.register('pokemon', PokemonViewSet, basename='pokemon')
router.register('type', TypeViewSet, basename='type')
router.register('users', UserViewSet,basename='users' )

# urlpatterns = [
#     path('', listPokemon.as_view()),
#     path('<int:pk>/', DetailPokemon.as_view()),
    
# ]
urlpatterns = router.urls + [
    path('activeuser/', ActiveUser.as_view())
]

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

pokedex_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    
    path('apis/v1/', include('apis.urls')),
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

pages/models.py
from django.db import models

# Create your models here.

pokemon/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Pokemon(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=200)
    height = models.FloatField()
    weight = models.FloatField()
    image_front = models.URLField()
    image_back = models.URLField()
    caught_by = models.ManyToManyField(get_user_model(), related_name='caught')
    # types = the set of Types associated with that Pokemon

    def __str__(self):
        return self.name

class Type(models.Model):
    type = models.CharField(max_length=50)
    pokemon = models.ManyToManyField(Pokemon, related_name='types')

    def __str__(self):
        return self.type
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass
    # caught = the set of Pokemon associated with that user

    # This is where you would add additional fields.
    # These will be in the DB alongside username, email, etc

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

apis/views.py
from django.shortcuts import render
from rest_framework import generics, viewsets
# Create your views here.
from pokemon.models import Pokemon, Type
from users.models import CustomUser
from .serializers import CustomUserSerializer, PokemonSerializer, TypeSerializer

# class listPokemon(generics.ListCreateAPIView):
#     queryset = Pokemon.objects.all()
#     serializer_class = PokemonSerializer
    
# class DetailPokemon(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Pokemon.objects.all()
#     serializer_class = PokemonSerializer
    

class PokemonViewSet(viewsets.ModelViewSet):
    queryset = Pokemon.objects.all()
    serializer_class = PokemonSerializer   
    
class TypeViewSet(viewsets.ModelViewSet):
    queryset = Type.objects.all()
    serializer_class = TypeSerializer 
    
class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer
    
class ActiveUser(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = CustomUserSerializer
    def get_object(self):
        return self.request.user

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'home.html'

pokemon/views.py
from django.shortcuts import render

users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>{% block title %}Pokedex{% endblock title %}</title>
  </head>
  <body>
    <div class="container-fluid m-0 p-0">
      {% block content %}
      <h3>you should't be here</h3>
      {% endblock content %}
    </div>
  </body>
</html>

templates/home.html
{% extends "_base.html" %} {% load static %} {% block content %}

{% if user.is_authenticated %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
    <div class="navbar-item">
        <h2>Welcome to {{ user.username }}'s Pokedex!</h2>
        <p><a href="{% url 'logout' %}">Logout</a></p>
        <p></p>
    </div>
    </nav>
    <main class="container mt-10">
    {% csrf_token %}
    <div class="" id="app">
        <div class="row d-flex justify-content-around">
            <div class="card mt-2 mx-1 rounded border border-info" style="width: 21rem;" v-for="item in catchPokemon" :key="item.id" :value="item.id">
                <div class="card-header container-fluid d-flex justify-content-around">
                    
                    <div class="position-absolute top-0 start-50 translate-middle">
                        <img src="static/media/icons8-superball-48.png" alt="captured-pokeball">
                    </div>
                    <img class="rounded float-start mx-1 px-1" :src="item.image_front" :alt="item.name">
                    <img class="rounded float-end mx-1 px-1" :src="item.image_back" :alt="item.name">
                </div>
                <div class="card-body">
                    <h4 class="card-title text-center">[[ item.name ]]</h4>
                    <hr>
                    <p class="card-text">Height: [[ item.height ]]</p>
                    <p class="card-text">Weight: [[ item.weight ]]</p>
                </div>
                <div class="card-footer btn-group d-flex justify-content-around" style="width: 21rem;">
                    <a class="rounded btn btn-outline-success btn-sm btn-block float-start mr-1 w-100 disabled" @click.prevent="caughtPokemon(item)">catch<br>[[item.name]]</a>
                    <a class="rounded btn btn-outline-warning btn-sm float-none mx-1 w-100 disabled" @click.prevent="releasedPokemon(item)">edit<br>[[item.name]]</a>
                    <a class="rounded btn btn-outline-danger btn-sm btn-block ml-1 w-100" @click.prevent="releasedPokemon(item)">release<br>[[item.name]]</a>
                </div> 
            </div>
        </div>
        <div class="row d-flex justify-content-around">
            <div class="card mt-2 mx-1 rounded border border-info" style="width: 21rem;" v-for="item in releasePokemon" :key="item.number">
                <div class="card-header container-fluid d-flex justify-content-around">
                    <img class="rounded float-start mx-1 px-1" :src="item.image_front" :alt="item.name">
                    <img class="rounded float-end mx-1 px-1" :src="item.image_back" :alt="item.name">
                </div>
                <div class="card-body">
                    <h4 class="card-title text-center">[[ item.name ]]</h4>
                    <hr>
                    <p class="card-text">Height: [[ item.height ]]</p>
                    <p class="card-text">Weight: [[ item.weight ]]</p>
                </div>
                <div class="card-footer btn-group d-flex justify-content-around" style="width: 21rem;">
                    <a class="rounded btn btn-outline-success btn-sm btn-block float-start mr-1 w-100" @click.prevent="caughtPokemon(item)">catch<br>[[item.name]]</a>
                    <a class="rounded btn btn-outline-warning btn-sm float-none mx-1 w-100 disabled" @click.prevent="releasedPokemon(item)">edit<br>[[item.name]]</a>
                    <a class="rounded btn btn-outline-danger btn-sm btn-block ml-1 w-100 disabled" @click.prevent="releasedPokemon(item)">release<br>[[item.name]]</a>
                </div> 
            </div>
        </div>

    </div>
{% else %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
        <div class="navbar-item">
        <h2>Welcome, visitor!</h2>
        <p>
            You are not logged in. <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'users:signup' %}">Sign Up</a>
        </p>
        </div>
    </nav>
    <h1>Welcome, visitor!</h1>
    <p>
        You are not logged in. <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:signup' %}">Sign Up</a>
    </p>
    <div class="row d-flex justify-content-around" id="app">
        <div class="card mt-2 mx-1 rounded border border-info" style="width: 21rem;" v-for="item in pokemon" :key="item.id">
            <div class="card-header container-fluid d-flex justify-content-around">
                <img class="rounded float-start mx-1 px-1" :src="item.image_front" :alt="item.name">
                <img class="rounded float-end mx-1 px-1" :src="item.image_back" :alt="item.name">
            </div>
            <div class="card-body">
                <h4 class="card-title text-center">[[ item.name ]]</h4>
                <hr>
                <p class="card-text">Type: [[ item.type ]]</p>
                <p class="card-text">Height: [[ item.height ]]</p>
                <p class="card-text">Weight: [[ item.weight ]]</p>
            </div>

        </div>
    </div>
{% endif %}
    </main>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script>
  new Vue({
    el: '#app',
    delimiters: ['[[', ']]'],
    data: {
      pokemon: [],
      csrfToken: '',
      users: [],
      activeUser: {},
      caught: [],
      uncaught: [],
    },
    methods: {
      loadPokemon: function () {
        console.log('loading pokemon');
        axios({
          method: 'get',
          url: '/apis/v1/pokemon/',
        }).then((response) => {
          console.log(response.data);
          this.pokemon = response.data;
        });
      },
      loadUsers: function () {
        console.log('loading users');
        axios({
          method: 'get',
          url: '/apis/v1/users/',
        }).then((response) => {
          console.log(response.data);
          this.users = response.data;
        });
      },
      loadActiveUser: function () {
        console.log('loading activeUser');
        axios({
          method: 'get',
          url: '/apis/v1/activeuser/',
        }).then((response) => {
          console.log(response.data);
          this.activeUser = response.data;
        });
      },
      caughtPokemon: function (pokemon) {
        this.activeUser.caught.push(pokemon.number)
        axios({
          method: 'patch',
          url: `/apis/v1/activeuser/`,
          headers: {
            'X-CSRFToken': this.csrfToken,
          },
          data: {
            caught: this.activeUser['caught'],
          },
        })
          .then((response) => {
            console.log(this.activeUser['caught'])
            console.log(pokemon)

            this.loadActiveUser();
          })
          .catch((err) => {
            console.log(err);
          });
      },
      releasedPokemon: function (pokemon) {
        this.activeUser.caught.splice(
          this.activeUser.caught.indexOf(pokemon.number),
          1
        );
        axios({
          method: 'patch',
          url: `/apis/v1/activeuser/`,
          headers: {
            'X-CSRFToken': this.csrfToken,
          },
          data: {
            caught: this.activeUser['caught'],
          },
        })
          .then((response) => {
            console.log(this.activeUser['caught'])
            this.loadActiveUser();
          })
          .catch((err) => {
            console.log(err);
          });
      },
    },

    created: function () {
      this.loadPokemon();
      this.loadUsers();
      this.loadActiveUser();
    },

    computed: {
      catchPokemon: function () {
        return this.pokemon.filter(pokemon => {
          return this.activeUser['caught'].includes(pokemon.number);
        });
      },
      releasePokemon: function () {
        return this.pokemon.filter(pokemon => {
          return !this.activeUser['caught'].includes(pokemon.number);
        })
      }
    },

    mounted: function () {
      this.csrfToken = document.querySelector(
        'input[name=csrfmiddlewaretoken]'
      ).value;
    },
  });
</script>
{% endblock content %}